name: Build

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    name: Build - ${{ matrix.job.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - { name: "x86_64",    wol_platform: "x86_64"  }
          - { name: "arm64-v8a", wol_platform: "aarch64" }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name:
        run: |
          echo ${{ matrix.job.name }}
