name: CI

on:
  # pull_request:
  push:
    tags: [ "v*" ]
    # branches: [ "master" ]
  # workflow_dispatch:

permissions:
  contents: write

env:
  ARCH: arm64-v8a

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Create file
        run: |
          mkdir -p build
          sleep 10
          tee build/update.json <<EOF
          {
            "key": "value",
            "arch": "${{ env.ARCH }}"
          }
          EOF
          < build/update.json

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/*
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}

  changelog:
    name: Changelog
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name:
        run: |
          sleep 5

      - name: Build changelog
        uses: mikepenz/release-changelog-builder-action@v5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          outputFile: CHANGELOG.md
          commitMode: true
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "categories": [
                {
                  "title": "## What's Changed",
                  "label": []
                }
              ]
            }

      - name: Upload to GitHub release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            CHANGELOG.md
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
          body_path: CHANGELOG.md
          generate_release_notes: true
